### ISSUE TITLE
composed-gradle-nexus-iq.yaml contains "action/setup-python"

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [lfit/releng-reusable-workflows#190]
Not sure this is needed in a workflow primarily working with Java code:
```
      # yamllint disable-line rule:line-length
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        id: setup-python
        with:
          python-version: "3.8"
```
I can't see anything that needs it; can somebody else eyeball this?
