### ISSUE TITLE
gradle-build action contains a hard-wired Java "distribution" value

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [lfit/releng-reusable-workflows#191]
I think this step might need some attention:
```
    - name: Setup JDK
      id: setup-jdk
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: "temurin"
```
Distribution is required, but could have multiple values, as per the documentation: 
https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions

Might be better to set this in an _optional_ input, with "temurin" as default value?
