### ISSUE TITLE
Issues with prettier and pre-commit hook

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [lfit/releng-reusable-workflows#230]
The current prettier repository used in our .pre-commit-config.yaml file is archived:

```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
```

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/0e88e8c1-cd4d-417a-a0f5-cb803e7656bf" />
<img width="959" alt="Image" src="https://github.com/user-attachments/assets/d2521ea0-897b-4ad9-9e0a-65abbdc12195" />

The primary/actual source repository is here:

https://github.com/prettier/prettier

<img width="832" alt="Image" src="https://github.com/user-attachments/assets/c76571b3-7eb4-43db-8f07-cd37198831d5" />

There'a also a bug fix we now need in the tagged 3.4.0 release:

https://prettier.io/blog/2024/11/26/3.4.0.html

See: https://github.com/prettier/prettier/pull/15526

Otherwise, markdownlint and prettier fight over bulleted items in markdown files, such as README.md.

Prettier will change:

```
- Item in list
- Second item in list
```

...adding spaces so that it reads:

```
-   Item in list
-   Second item in list
```

...markdownlint will then, quite correctly, revert the above change.

I can only suggest removing prettier for the moment, as it looks like running it from pre-commit requires us to jump through some hoops?
