### ISSUE TITLE
The standalone-linting-action should check for a local pre-commit file

### ISSUE THREAD

**Issue by ModeSevenIndustrialSolutions** [lfit/releng-reusable-workflows#245]
We should enhance the functionality of this action:
https://github.com/lfit/releng-reusable-workflows/tree/main/.github/actions/standalone-linting-action

Check for a local .pre-commit-config.yaml file prior to calling:
```yaml
    - name: "Download pre-commit configuration file"
      shell: bash
      run: |
        # Download pre-commit configuration file
        echo "Downloading configuration from: ${{ inputs.CONFIG_URL }}"
        curl -sS -o .pre-commit-config.yaml "${{ inputs.CONFIG_URL }}"
        echo "Pre-commit configuration file downloaded ✅"
        cat .pre-commit-config.yaml
```
